#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)

git submodule update --init --recursive
echo "[INFO] submodules initialized"

(cd mpl && smlpkg sync)
echo "[INFO] smlpkg lib sync'ed"

./generate-inputs
echo "[INFO] inputs generated"

echo "Skip installng MPLs"
# $ROOT/scripts/install_mpls
