#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=scripts/gencmds
RUN=scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/results
RESULTS=$ROOT/results/$NOW

rm -f $ROOT/mpl/bin/*.bin

# Get experiments for 'mpl'
# We use a temporary file to avoid running gencmds twice
TMP=$(mktemp)
# Use `exp-small` to just run single-threaded time tests
$GEN $@ $ROOT/exp-small.json | jq -c 'select(.config == "mpl")' > "$TMP"

# Run experiments for both 'mpl' and 'mpl-baseline'
# We take the 'mpl' experiments and also generate 'mpl-baseline' experiments
# by changing the config name and binary name in the command string.
( \
  cat "$TMP"; \
  jq -c '.config = "mpl-baseline" | .cmd |= sub("\\.mpl\\.bin"; ".mpl-baseline.bin")' "$TMP" \
) | $RUN --compile --output $RESULTS

rm "$TMP"

echo "[INFO] wrote results to $RESULTS"
