#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=scripts/gencmds
RUN=scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/results
RESULTS=$ROOT/results/$NOW

rm -f $ROOT/mpl/bin/*.bin

$GEN $@ $ROOT/exp.json | jq -c 'select(.config == "mpl")' | $RUN --compile --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
